name: BJP Keep
slug: bjpkeep
version: "0.1.0"
description: "Where is my stuffs."
startup: application
boot: auto
init: false
panel_icon: mdi:package-variant-closed
webui: http://[HOST]:[PORT:3000]
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: BJP Keep Web UI
arch:
  - amd64
  - aarch64
  - armv7
