name: BJP Keep
slug: bjpkeep
version: "0.4.4"
description: "BJP Home where are my stuff!!"
startup: application
boot: auto
init: false
panel_icon: mdi:package-variant-closed
ingress: true
ingress_port: 3000
arch:
  - amd64
  - aarch64
  - armv7
map:
  - share:rw
options:
  log_level: info
  app_url: ""
  dev_mode: false
schema:
  log_level: "list(debug|info|warning|error|fatal)"
  app_url: "str?"
  dev_mode: bool
