name: BJP Keep
slug: bjpkeep
version: "0.7.0d"
description: "BJP Home where are my stuff!!"
startup: application
boot: auto
init: false
panel_icon: mdi:package-variant-closed
ingress: true
ingress_port: 3000
homeassistant_api: true
ports:
  3000/tcp: 3000
arch:
  - amd64
  - aarch64
  - armv7
map:
  - share:rw
options:
  log_level: info
  app_url: ""
  lovelace_token: ""
  niimbot_label_device_id: ""
  niimbot_qr_device_id: ""
  dev_mode: false
schema:
  log_level: "list(debug|info|warning|error|fatal)"
  app_url: "str?"
  lovelace_token: "str?"
  niimbot_label_device_id: "str?"
  niimbot_qr_device_id: "str?"
  dev_mode: bool
