import { NextRequest, NextResponse } from "next/server";

export async function middleware(req: NextRequest) {
  const ingressHeader = req.headers.get("x-ingress-path") || "";
  const ingressCookie = req.cookies.get("bjpkeep-ingress-path")?.value || "";
  const ingressPath = ingressHeader || ingressCookie;
  
  const { pathname } = req.nextUrl;

  // Compute the internal path by stripping the ingress prefix if it exists
  let internalPath = pathname;
  if (ingressPath && pathname.startsWith(ingressPath)) {
    internalPath = pathname.replace(ingressPath, "") || "/";
  }

  // Define response
  let res: NextResponse;

  // IMPORTANT: If we detect a request to /api, /_next, or /uploads that IS NOT 
  // prefixed but we have an ingress path from a cookie, we MUST rewrite it.
  // This catches absolute URLs generated by Next.js or third party libs.
  const isAssetOrApi = 
    pathname.startsWith("/_next") || 
    pathname.startsWith("/api") || 
    pathname.startsWith("/uploads") ||
    pathname === "/favicon.ico";

  if (isAssetOrApi && !pathname.startsWith(ingressPath) && ingressPath) {
    res = NextResponse.rewrite(new URL(pathname, req.url));
  } else if (internalPath !== pathname) {
    res = NextResponse.rewrite(new URL(internalPath, req.url));
  } else {
    res = NextResponse.next();
  }

  // Always refresh the ingress path cookie
  if (ingressPath) {
    res.cookies.set("bjpkeep-ingress-path", ingressPath, { 
      path: "/", 
      sameSite: "lax",
      maxAge: 60 * 60 * 24 // 1 day
    });
  }

  return res;
}

export const config = {
  matcher: ["/:path*"],
};
